name: RKStudio Cypress testing

on: [push]
env:
  QT_X11_NO_MITSHM: 1
  _X11_NO_MITSHM: 1
  _MITSHM: 0
  CI: 1

jobs:
  cypress-run:
    runs-on: ubuntu-latest
#    container:
#      image: cypress/browsers:node17.8.0-chrome99-ff97-slim
#      options: --user root -v ${{ github.workspace }}:/zap/wrk/:rw

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 17

      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Starting Cypress tests
        uses: cypress-io/github-action@v4.2.0
        with:
          browser: chrome
          run: npm run cy:only_run_one_spec

      - run: npm run slack:publish
      - run: npm run allure:report & allure:server

#      - name: Send report to slack
#        uses: cypress-io/github-action@v4.2.0
#        with:
#          browser: chrome
#          build: npm run slack:publish
#
#      - name: Allure report
#        uses: cypress-io/github-action@v4.2.0
#        with:
#          browser: chrome
#          build: npm run allure:report & allure:server

      - name: Publish report
        uses: pavi2410/html-preview-action@v2
        with:
            html_file: 'allure-report/index.html'

      - name: Send GitHub Action trigger data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          # This data can be any valid JSON from a previous step in the GitHub Action
          payload: |
            {
              "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "GitHub Action build result: ${{ job.status }}\n
                    ${{ github.event.pull_request.html_url || github.event.head_commit.url }}\n
                    Web Reports: ${{ steps.html_preview.outputs.url }}"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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
#          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Allure report artifact
        uses: actions/download-artifact@v2
        with:
          name: Allure report
          path: allure-report

      - name: Allure results artifact
        uses: actions/download-artifact@v2
        with:
          name: Allure results
          path: allure-results

      - name: Slack report artifact
        uses: actions/download-artifact@v2
        with:
          name: Slack
          path: reports