name: RKStudio Cypress testing

on: [ push ]
env:
  QT_X11_NO_MITSHM: 1
  _X11_NO_MITSHM: 1
  _MITSHM: 0
  CI: 1

jobs:
  install:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node17.8.0-chrome99-ff97-slim
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress install
        uses: cypress-io/github-action@v4
        with:
          runTests: false
      # report machine parameters
      - run: yarn cypress info
      - run: node --version
      - run: node -p 'os.cpus()'
  #
  #      - name: Save build folder
  #        uses: actions/upload-artifact@v3
  #        with:
  #          name: build
  #          if-no-files-found: error
  #          path: build

  cypress-run:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node17.8.0-chrome99-ff97-slim
      options: --user 1001
    needs: install
    strategy:
      # when one test fails, DO NOT cancel the other
      # containers, because this will kill Cypress processes
      # leaving the Dashboard hanging ...
      # https://github.com/cypress-io/github-action/issues/48
      fail-fast: false
      matrix:
        # run copies of the current job in parallel
        containers: [ 1 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      #      - name: Download the build folders
      #        uses: actions/download-artifact@v3
      #        with:
      #          name: build
      #          path: build

      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Starting Cypress tests
        uses: cypress-io/github-action@v4.2.0
        with:
          runTests: false
          build: npm run cy:only_run_one_spec

      - name: Save Slack report
        uses: actions/upload-artifact@v3
        with:
          name: slack_report
          if-no-files-found: error
          path: |
            reports
            allure-results

  allure-report:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node17.8.0-chrome99-ff97-slim
      options: --user 1001
    needs: cypress-run
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download reports
        uses: actions/download-artifact@v3
        with:
          name: slack_report
          if-no-files-found: error

      - name: Install Cypress
        uses: cypress-io/github-action@v4.2.0
        with:
          runTests: false

      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '11'

      - run: npm run allure:report

      - name: Save Allure report
        uses: actions/upload-artifact@v3
        with:
          name: allure_report
          if-no-files-found: error
          path: allure-report

  slack-report:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node17.8.0-chrome99-ff97-slim
      options: --user 1001
    needs: cypress-run
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download reports
        uses: actions/download-artifact@v3
        with:
          name: slack_report
          if-no-files-found: error

      - name: Publishing Slack report
        uses: cypress-io/github-action@v4.2.0
        with:
          runTests: false
          build: npm run slack:publish

  publish-allure-report:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node17.8.0-chrome99-ff97-slim
      options: --user 1001
    needs: allure-report
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download Allure Report
        uses: actions/download-artifact@v3
        with:
          name: allure_report
          if-no-files-found: error

      - name: Install Cypress
        uses: cypress-io/github-action@v4.2.0
        with:
          runTests: false

      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '11'

      - name: Publishing report
        uses: pavi2410/html-preview-action@v2
        with:
          html_file: 'allure-report/index.html'

  send-published-allure-report-to-slack:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node17.8.0-chrome99-ff97-slim
      options: --user 1001
    needs: publish-allure-report
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download Allure Report
        uses: actions/download-artifact@v3
        with:
          name: allure_report
          if-no-files-found: error

      - name: Install Cypress
        uses: cypress-io/github-action@v4.2.0
        with:
          runTests: false

      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '11'

      - name: Send GitHub Action trigger data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          # This data can be any valid JSON from a previous step in the GitHub Action
          payload: |
            {
              "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "GitHub Action build result: ${{ job.status }}\n
                    ${{ github.event.pull_request.html_url || github.event.head_commit.url }}\n
                    Web Reports: ${{ steps.html_preview.outputs.url }}"
                  }
                }
              ]
            }
          env:
            SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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
          #          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

#  Reporter:
#    timeout-minutes: 15
#    runs-on: ubuntu-latest
#    container:
#      image: cypress/browsers:node17.8.0-chrome99-ff97-slim
#      options: --user 1001
#    needs: cypress-run
#      steps:
#          - run: npm run slack:publish
#            - run: npm run allure:report & allure:server
#
#                #      - name: Send report to slack
#                #        uses: cypress-io/github-action@v4.2.0
#                #        with:
#                #          browser: chrome
#                #          build: npm run slack:publish
#                #
#                #      - name: Allure report
#                #        uses: cypress-io/github-action@v4.2.0
#                #        with:
#                #          browser: chrome
#              #          build: npm run allure:report & allure:server
#
#            - name: Publish report
#              uses: pavi2410/html-preview-action@v2
#              with:
#                html_file: 'allure-report/index.html'
#
#            - name: Send GitHub Action trigger data to Slack workflow
#              id: slack
#              uses: slackapi/slack-github-action@v1.23.0
#              with:
#                # This data can be any valid JSON from a previous step in the GitHub Action
#                payload: |
#                  {
#                    "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
#                    "blocks": [
#                      {
#                        "type": "section",
#                        "text": {
#                          "type": "mrkdwn",
#                          "text": "GitHub Action build result: ${{ job.status }}\n
#                          ${{ github.event.pull_request.html_url || github.event.head_commit.url }}\n
#                          Web Reports: ${{ steps.html_preview.outputs.url }}"
#                        }
#                      }
#                    ]
#                  }
#                env:
#                  SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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
#                #          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
#
#                - name: Allure report artifact
#                  uses: actions/download-artifact@v2
#                  with:
#                    name: Allure report
#                    path: allure-report
#
#                - name: Allure results artifact
#                  uses: actions/download-artifact@v2
#                  with:
#                    name: Allure results
#                    path: allure-results
#
#                - name: Slack report artifact
#                  uses: actions/download-artifact@v2
#                  with:
#                    name: Slack
#                    path: reports